### ISSUE TITLE
Cannot hide process files

### ISSUE THREAD

**Issue by ttsite** [S12cybersecurity/S12URootkit#1]
After testing, it was found that files cannot be hidden in the Task Manager process. The testing system is Windows 7 and Windows 10

**Comment by S12cybersecurity** [comment]
Output error or something?

You Execute as Administrator?

**Comment by ttsite** [comment]
> Output error or something?
> 
> You Execute as Administrator?

yes

**Comment by S12cybersecurity** [comment]
But in Task Manager you hide process no files.

Wait 2 hours i will publish in the readme a video tutorial about the usage of this tool

**Comment by S12cybersecurity** [comment]
Check now the usage basic of this Rootkit, if the issue persist  put a note here
